update padlock display behaviour
UoA-eResearch/hub-stack pull request #114
Opened 2021-07-20 00:36 UTC by robmint

Padlocks be like...

<img width="261" alt="Screen Shot 2021-07-20 at 12 35 17 PM" src="https://user-images.githubusercontent.com/133544/126244667-6ef0b792-e112-4bb9-8bcf-17d64b75be1a.png">
<img width="331" alt="Screen Shot 2021-07-20 at 12 35 11 PM" src="https://user-images.githubusercontent.com/133544/126244671-297076d2-5f10-4d95-920b-d89c0616f2e1.png">

2021-07-20 00:38 UTC, robmint commented
Apologies for use of auto-format feature, which obscures the real changes somewhat.

2021-07-20 02:07 UTC, rosemcc commented
> Apologies for use of auto-format feature, which obscures the real changes somewhat.

I want to create a branch where I go through and autoformat EVERYTHING!!! Haha

2021-07-20 02:20 UTC, rosemcc commented on research-hub-web/src/app/components/shared/body-media/body-media.component.html
> +                                <mat-icon *ngIf="contentItem.ssoProtected" matTooltip="SSO Login Required">lock</mat-icon>
do we need &nbsp; here too?

2021-07-20 04:15 UTC, rosemcc requested changes
Looks good, just need to address the comment I left about the Link Card

2021-07-21 22:24 UTC, rosemcc approved these changes

2021-08-02 22:16 UTC, merged