View switcher
UoA-eResearch/hub-stack pull request #37
Opened 2020-10-22 01:28 UTC by warrickct

* Contains updated graphql query to include the viewType field.
* Adds dynamic view switching for the subhub pages based on contentful response data.

2020-10-29 21:29 UTC, JuliusKarl commented
- Initial wireframes for ResearchHub Expansion redesign (_Article and Equipment_)
- View Switches (_2 Options_) from Contentful Option
- Additional GraphQL Query implemented to bypass complexity issue (_GetArticleByID_ and _GetEquipmentByID_)

2020-10-29 22:59 UTC, Hganavak requested changes
Same as #38,  @warrickct  if you can make the requested changes to #36. We'll get those merged into `master`, then you can just merge `master` into these 2 branches, re-request review and be good to go :v:

2020-11-05 02:52 UTC, warrickct commented on Jenkinsfile
> +                            steps {
These changes had to be done on sandbox in order to test the deployment functionality.

2020-11-05 02:54 UTC, warrickct commented on research-hub-web/e2e/app.e2e-spec.ts
> -  it('can browse by category', async () => {
Assuming this is us disabling protractor e2e tests for now?

2020-11-05 03:01 UTC, warrickct commented on research-hub-web/src/app/components/equipment/equipment.component.ts
> +  // public assets: Array<any>;
Old code comments probably best to remove.

2020-11-05 03:10 UTC, warrickct reviewed
Looks fine to me aside from some bits of old code to be tidied up.

2020-11-05 03:10 UTC, warrickct commented on research-hub-web/src/app/components/articles/articles.component.ts
> +        // this.article$.subscribe(data => {
Code comments to be removed.

2020-11-05 03:10 UTC, warrickct commented on research-hub-web/src/styles.scss
>  h4 {
In the file above "research-hub-web/src/assets/env.js" if it's empty can this be deleted?

2020-11-05 03:10 UTC, warrickct commented on research-hub-web/src/app/components/equipment/equipment.component.ts
> +        // this.equipment$.subscribe(data => {
Old code to delete

2020-11-05 03:10 UTC, warrickct commented on research-hub-web/src/app/components/articles/articles.component.ts
> +        // this.article$.subscribe(data => {
old code to delete

2020-11-05 03:10 UTC, warrickct commented on research-hub-web/src/app/components/articles/articles.component.ts
> +  // public assets: Array<any>;
old code to delete

2020-11-05 03:13 UTC, warrickct commented
I saw a file "research-hub-web/src/assets/env.js" which is supposedly empty. If it's empty can this be deleted?

2020-11-08 22:12 UTC, warrickct commented
@JuliusKarl These are the layout issues I was referring to this morning. The issues are mostly improvements for 4k displays.

* Home page icons could be enlarged.
* New banner titles could be enlarged. 
* There seems to be a bug where a banner in image 2 but I haven't been able to recreate it. Sam said it popped up when he navigated between pages somehow.

I'll have another check to see if there's anything else.

![image (4)](https://user-images.githubusercontent.com/24505032/98485361-c61bd780-227a-11eb-91a5-a7a62b656f7d.png)
---
![image](https://user-images.githubusercontent.com/24505032/98485284-36762900-227a-11eb-9d60-10e3c739a988.png)
---
![image (1)](https://user-images.githubusercontent.com/24505032/98485290-3b3add00-227a-11eb-9f36-ae99a786ce3a.png)
---
![image (3)](https://user-images.githubusercontent.com/24505032/98485307-573e7e80-227a-11eb-9748-74204c7637af.png)

2020-11-11 02:14 UTC, warrickct reviewed
@JuliusKarl Hey, I noticed a couple of things. Not sure if they're specific to my machine. Could you please run a deployment of all projects? It's so I can see that the serverless and cer-graphql subrepos tests are working as well.

* There seems to be a small strip of another image just above the banner on articles pages. Looks fine for equipment though.
<img width="815" alt="Screen Shot 2020-11-11 at 2 54 29 PM" src="https://user-images.githubusercontent.com/24505032/98756688-ef319900-242f-11eb-890e-e7b6d4b5becc.png">

---

* The option tile headers are very small
<img width="815" alt="Screen Shot 2020-11-11 at 2 56 36 PM" src="https://user-images.githubusercontent.com/24505032/98756732-03759600-2430-11eb-9998-f0f8cfa1a7e6.png">

---

* I'm signed in but unable to see any content for the top secret article.
<img width="1026" alt="Screen Shot 2020-11-11 at 2 57 26 PM" src="https://user-images.githubusercontent.com/24505032/98756747-096b7700-2430-11eb-9815-454423db8ca2.png">

2020-11-11 03:34 UTC, JuliusKarl commented
Hopefully Resolved the latest comments

- The strip is from the original photo
- The font-size is relative to browser size now
- The 'top-secret-entry' was missing a _required_ viewType which is why it was blank. Should be visible now

2020-11-12 00:03 UTC, warrickct commented
Ahh ok, my mistake about the top-secret and original photo points. All the tests are passing on my side and it looks all good. Feel free to merge 👍👍 .

2020-11-12 01:43 UTC, merged